name: 'credit_default_env'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib>=3.2.2
  - scikit-learn>=1.0
  - pandas>=1.3.*
  - requests>=2.24.0
  - altair 
  - vega_datasets
  - graphviz
  - python-graphviz
  - jinja2
  - pip
  - lightgbm
  - py-xgboost==1.3.0
  - catboost
  - spacy
  - wikipedia
  - nltk
  - eli5
  - shap
  - seaborn
  - imbalanced-learn
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - docopt==0.6.2
  - openpyxl==3.0.9
  - xlrd==2.0.1
  - altair==4.1.0
  - portpicker==1.5.0
  - jupyterlab==3.2.4
  - pip:
    - mglearn
    - psutil>=5.7.2

